### https://github.com/plantuml/plantuml-server

@startuml FeedrScheme
class Vote {
    id: Int
    score: Int
    comment: String
    servant: Servant
    client: Client
    time: DateTime
    +addVote()
    +editVote()
    +deleteVote()
    +showWorkerVotes()
    +showClientVotes()
}
note bottom of Vote
  /votes
  /vote/id
end note

class Servant {
    id: Int
    name: String
    rating: Double
    +addServant()
    +editServant()
    +deleteServant()
    +getRating()
}
note bottom of Servant
  /servant
  /servant/id
end note

class Client {
    id: Int
    name: String
    phone: Int
}
Servant -> Vote
Client -> Vote
@enduml